command_timeout = 2000

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:#212736 bg:#1d2230)\
$docker_context\
$aws\
$kubernetes\
[ ](fg:#1d2230)\
\n$status$character"""

right_format = """$cmd_duration$time"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰆚 "
"Music" = "󰀁 "
"Pictures" = "󰏨 "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version)(\($virtualenv\)) ](fg:#769ff0 bg:#212736)]($style)'

[docker_context]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol $context ](fg:#a0a9cb bg:#1d2230)]($style)'
only_with_files = false

[aws]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol ($profile)(\($region\)) ](fg:#a0a9cb bg:#1d2230)]($style)'

[kubernetes]
symbol = "󱃾"
style = "bg:#1d2230"
format = '[[ $symbol $context(\($namespace\)) ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[cmd_duration]
min_time = 2_000
format = '[ 󱎫 $duration](fg:#a0a9cb)'

[time]
disabled = false
time_format = "%R"
format = '[  $time](fg:#a0a9cb)'

[status]
disabled = false
symbol = '✘'
format = '[$symbol$status ]($style)'
style = 'fg:#e06c75'
